  --Btp
   ['b_oil_refiner'] = 'Entreprise BTP',
   ['b_drill_oil'] = 'Sand Mine',
   ['b_fuel'] = 'Gravel',
   ['b_drillbutton'] = 'press ~ INPUT_PICKUP ~ to recover.',
   ['b_fuel_refine'] = 'Transformation 1',
   ['b_refine_fuel_button'] = 'press ~ INPUT_PICKUP ~ to transform.',
   ['b_fuel_mixture'] = 'Transformation 2',
   ['b_gas'] = 'Cement',
   ['b_fuel_mixture_button'] = 'press ~ INPUT_PICKUP ~ to transform.',
   ['b_deliver_gas'] = "press ~ INPUT_PICKUP ~ to deliver the cement.",